<?php

/**
 * @category    ScandiPWA
 * @package     ScandiPWA_Customization
 * @copyright   Copyright © 2021 Scandiweb, Ltd (http://scandiweb.com)
 * @copyright   Modifications © Selveq. All rights reserved.
 * @license     http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 * @license     OSL-3.0 (Open Software License ("OSL") v. 3.0)
 * See LICENSE for license details.
 */
?>

<?php $scandiPwaVersion = $block->getScandiPWAVersion(); ?>
<?php if ($scandiPwaVersion) : ?>
    <p class="scandipwa-version">
        <strong><?= $block->escapeHtml(__('ScandiPWA')) ?></strong>
        <?= $block->escapeHtml(__('ver. %1', $scandiPwaVersion)) ?>
    </p>
<?php endif; ?>
<p class="magento-version">
    <strong><?= $block->escapeHtml(__('Magento')) ?></strong>
    <?= $block->escapeHtml(__('ver. %1', $block->getMagentoVersion())) ?>
</p>
